In [3]:
import numpy as np
import statistics

[[]]


In [41]:
z = np.random.randint(101, size=(751, 6))       #
print("  P  C  M  B  H  Py")
print(z)

  P  C  M  B  H  Py
[[10 22 68 77 28 65]
 [40 24 47  4 40 72]
 [ 5 26 82 48 76 24]
 ..., 
 [73  2 76 30 64 83]
 [58  3 38 13 61 22]
 [20 32 29 36 79  5]]


In [43]:
print(z[:,0])
print(z[:,0].shape)
# z[750]=np.array[100 100 100 100 100 100]
print(z[749])
z[750] = 100
print(z)

[ 10  40   5  71   1  10  97  54  96  48  33  54   6  10  64  66   4  28
 100  25  29  65  93  72  49  35  41  55  62  99  49  88  41  21   4  70
  31 100   4  27  76  14   9  54  86  21 100   9  49  64  58  53  97  85
  70  29  75   0  77   6  98  79  92  76  13  19  45  76  82  43  67  76
  84  15  15  36  29  64  28  97  29  14  19  65   5  52   9  76  42  51
  47   4  38  84   2  66  56  75  59  14  18  79  38  39  60  86  10  50
  58   9  94   5   6  91  94  39  28  79  96  13  88  56  90  77  73   9
  89  48  50   3  34  72  66  28  44  14  55  93  93  29   6  20   4  70
  23  31   7  69  58  81   4   1  41   4  78  40   6  34  95  37  45  59
  15  31  24   6  87  12  27   4  12  75  14  68  85  45  60  55  33  82
  39  26  28  76  81   3  21  81   3  19  18  62  76  57  73  94  18   4
  99  85  12  51  68  46  99  70  36  85   1  28  21  54  54  82  73  70
  51  85  70  85  71  67  65  86  20  91  35  88  70  70  82   2  93  79
  58  22 100  54  30  43  32   0  18  70  71  24  8

In [ ]:

for i in range(750):
    
    

In [47]:
for i in range(6):
    col = z[:,i]
    for value in z[:,i]:
        print(value)

10
40
5
71
1
10
97
54
96
48
33
54
6
10
64
66
4
28
100
25
29
65
93
72
49
35
41
55
62
99
49
88
41
21
4
70
31
100
4
27
76
14
9
54
86
21
100
9
49
64
58
53
97
85
70
29
75
0
77
6
98
79
92
76
13
19
45
76
82
43
67
76
84
15
15
36
29
64
28
97
29
14
19
65
5
52
9
76
42
51
47
4
38
84
2
66
56
75
59
14
18
79
38
39
60
86
10
50
58
9
94
5
6
91
94
39
28
79
96
13
88
56
90
77
73
9
89
48
50
3
34
72
66
28
44
14
55
93
93
29
6
20
4
70
23
31
7
69
58
81
4
1
41
4
78
40
6
34
95
37
45
59
15
31
24
6
87
12
27
4
12
75
14
68
85
45
60
55
33
82
39
26
28
76
81
3
21
81
3
19
18
62
76
57
73
94
18
4
99
85
12
51
68
46
99
70
36
85
1
28
21
54
54
82
73
70
51
85
70
85
71
67
65
86
20
91
35
88
70
70
82
2
93
79
58
22
100
54
30
43
32
0
18
70
71
24
80
77
71
64
64
33
32
44
62
46
34
81
97
85
57
5
6
74
76
21
59
3
4
62
63
65
49
91
24
22
6
24
85
46
90
91
89
1
2
0
55
33
92
48
7
64
41
33
55
15
65
76
26
51
29
38
14
9
98
57
31
12
73
97
90
89
5
6
92
99
47
16
0
39
25
51
96
2
86
78
58
86
16
2
8
63
47
0
9
71
4
52
96
31
70
56
39
47
64
42
12
33
25
19